-- 코드를 입력하세요
SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(A.START_DATE), A.CAR_ID
HAVING CAR_ID IN (SELECT A.CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
                  WHERE A.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                  GROUP BY A.CAR_ID
                  HAVING COUNT(*) >= 5)
ORDER BY MONTH ASC, CAR_ID DESC